### ISSUE TITLE
There is no confirmation message when a user is deleted

### ISSUE THREAD

**Issue by LucileDT** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/huntington-avenir-bdd#13]
#### Pages
- On user edition page
- On user details page

#### Scenario
Delete the user

#### Wanted behaviour
A confirmation message is shown explaining user has been succesfully deleted

#### Current behaviour
User is deleted but no message is shown

**Comment by Parmifer** [comment]
Validated. Closing issue.
