### ISSUE TITLE
Add success/error messages on all actions

### ISSUE THREAD

**Issue by LucileDT** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/huntington-avenir-bdd#15]
# Context
The app is missing a lot of success and error messages. We need to check the actions and display nice messages for it.

# Todo
- [x] user creation
- [x] user edition
- [x] user connection
- [x] user logout

**Comment by sapphaos** [comment]
For user connection and user logout : methods loginAction and logoutAction of LoginController.php are never called, so the messages do not work.

**Comment by Yann-BUTSCHER-EIRL** [comment]
The FlashBag being stored in session, we can't display the saved message on logout success since the session is cleared on logout.
