### ISSUE TITLE
Customize HTML error pages

### ISSUE THREAD

**Issue by LucileDT** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/huntington-avenir-bdd#16]
# Context
Symfony provides ugly HTML error pages (like the 404 one). We should edit them for our own ones to make uniform the app.

# Todo
- [x] think about a page design
- [x] do the design for all the error pages

**Comment by Yann-BUTSCHER-EIRL** [comment]
https://symfony.com/doc/3.4/controller/error_pages.html

**Comment by LucileDT** [comment]
The 40x are fine, 50x too but generic ones are badly displayed:
![a screenshot showing that the error block is wider than it should be](https://user-images.githubusercontent.com/23707217/59506638-0a9a1c80-8ea9-11e9-8690-597e229e2490.png)

**Comment by LucileDT** [comment]
To display error pages in dev env:
- log in as admin
- use the URL http://projet-rul:project-port/_error/{error code}, e.G. in my env: http://127.0.0.1:8000/_error/404
