### ISSUE TITLE
Typos in roles descriptions

### ISSUE THREAD

**Issue by sapphaos** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/huntington-avenir-bdd#24]
There are a few typos for some roles descriptions :

# Scenario

# Expected behavior

Adhérent.e description :

> Permet de recevoir la newletter, les convocations à l'AG, les invitations aux événements, de consulter les documents des AG des années de cotisation, de voir les événements \"privés\" et de renouveler son 

Ex-adhérent.e description 

> Permet de recevoir une relance pour adhérer à l''association, renouveler son adhésion et  consulter les documents des AG des années de cotisation.

Inscrit.e

> Permet de voir les informations de son compte, de les éditer, de les archiver et de demander l'accès à l'annuaire des professionnels de santé.

# Current behavior 

Adhérent.e description :

> Permet de recevoir la newletter, les convocations à l'AG, les invitations aux événements, de consulter les documents des AG des années de cotisation, de voir les événements \"privés\" et de renouveller son 

Ex-adhérent.e description 

> Permet de recevoir une relance pour adhérer à l''association, renouveller son adhésion et  consulter les documents des AG des années de cotisation.

Inscrit.e description

> Permet de voir les informations de son compte, de les éditer, de les archiver et de demander l'accès à l'annuraire des professionels de santé.

# Todo

 - [x] Change "renouveller" to "renouveler" for Adhérent.e and Ex-adhérent.e
 - [x] Change "annuraire des professionels" to "annuaire des professionnels" for Inscrit.e

**Comment by LucileDT** [comment]
I would say as @hundrix mentionned that `newletter` is incorrect in English, therefore we should use `newsletter` instead.
