### ISSUE TITLE
Graphical bug in the animation of "card menu" of the administration page

### ISSUE THREAD

**Issue by ChangelinPipou** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/huntington-avenir-bdd#43]
# Scenario
Connect as admin (admin, a), go to the administration page, hover on the "gestion des utilisateurices" card
# Expected behavior
Animation of the card, nothing happen elsewhere

# Current behavior
During the animation, the scrollbar appear briefly, shifting the page to the left

![bug_admin_card](https://user-images.githubusercontent.com/50904753/59341817-d7208c00-8d08-11e9-998d-5e197065f017.gif)

**Comment by LucileDT** [comment]
In your opinion, would it be better to find why the scrollbar appears and fix it (it can take a very long time) or just always display the scroll bar, even it the page is small?

**Comment by ChangelinPipou** [comment]
Hum, always displaying the scroll bar is in my opinion the best solution. Not very elegant but it doesn't prevent any functionality or usability

**Comment by LucileDT** [comment]
And it is **a lot** easier than searching where the problem is coming from in the first case!
