### ISSUE TITLE
Phone numbers in forms should refuse text input

### ISSUE THREAD

**Issue by sapphaos** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/huntington-avenir-bdd#55]
# Scenario
New and Edit member forms.

# Expected behavior
The field should shouldn't accept text inputs.

# Current behavior
The field accepts any input.

**Comment by LucileDT** [comment]
Created #65 about the phone numbers

**Comment by LucileDT** [comment]
The verification are done in the front but not in the back end, so if I edit the HTML by hand or use something like cURL to send the form, I can still manage to save a phone number at for example `aaaaa`.

Please check it on backend
