### ISSUE TITLE
All fields in member creation form are required

### ISSUE THREAD

**Issue by LucileDT** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/huntington-avenir-bdd#59]
# Scenario
- connect as gestionnaire
- go to the form to create a new member
- enter a dénomination, a prénom and a nom
- submit the form

# Expected behavior
- only specific fields must be required
- required fields must have a `*` after their label

# Current behavior
- none of the fields have a `*` after their labels
- all the fields are required

**Comment by Yann-BUTSCHER-EIRL** [comment]
We can't create a People entity without address for now.
We need to find a proper way to handle this but this seems a bit complicated.
Documentation can be found here : https://symfony.com/doc/3.4/reference/forms/types/collection.html#allow-add

**Comment by Yann-BUTSCHER-EIRL** [comment]
https://symfony.com/doc/3.4/form/use_empty_data.html is another lead
