### ISSUE TITLE
Member creation does not work

### ISSUE THREAD

**Issue by LucileDT** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/huntington-avenir-bdd#61]
# Scenario
- connect as admin
- try to create a new member

# Expected behavior
- the new member is created

# Current behavior
- an exception is thrown
![image](https://user-images.githubusercontent.com/23707217/61140632-0d9a2400-a4cc-11e9-92ee-140212a813d0.png)

**Comment by LucileDT** [comment]
https://symfony.com/doc/3.4/form/form_collections.html we need to check this doc and adapt it to our needs

**Comment by Yann-BUTSCHER-EIRL** [comment]
We need to find a proper way to handle this but this seems a bit complicated.
Documentation can be found here : https://symfony.com/doc/3.4/reference/forms/types/collection.html#allow-add
https://symfony.com/doc/3.4/form/use_empty_data.html could be another lead

**Comment by sapphaos** [comment]
![image](https://user-images.githubusercontent.com/26595575/62447283-5492d680-b765-11e9-8856-79b6a87332ba.png)

![image](https://user-images.githubusercontent.com/26595575/62447332-7429ff00-b765-11e9-8e4d-b729fc3f2387.png)

I'm now having this error when creating a member with no address
