### ISSUE TITLE
User deletion doesn't work

### ISSUE THREAD

**Issue by Yann-BUTSCHER-EIRL** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/huntington-avenir-bdd#67]
# Scenario

1. Connect as admin.
2. Go to the administration page
3. Go the user list page
4. Click on edit a user
5. Delete the user (confirmation needed)

# Expected behavior
The user should be deleted and we should be redirected on the user list

# Current behavior
Symfony throws an error : 
```
An exception occurred while executing 'DELETE FROM user WHERE id = ?' with params [9]:

SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`erp-asso-test`.`people`, CONSTRAINT `FK_28166A26A76ED395` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`))
```

**Comment by LucileDT** [comment]
Still bugged

![image](https://user-images.githubusercontent.com/23707217/62294413-24002380-b46b-11e9-9ccb-26339a884fd1.png)
