### ISSUE TITLE
Profile roles edit doesn't redirect 

### ISSUE THREAD

**Issue by sapphaos** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/huntington-avenir-bdd#82]
# Scenario
Connect with a user
Go to their profile
Edit their roles

# Expected behavior
The redirection should redirect to the editroles page

# Current behavior
It doesn't redirect because it needs the username in the form

![image](https://user-images.githubusercontent.com/26595575/62452133-e273bf00-b76f-11e9-83e7-9061f16f3dfe.png)

**Comment by LucileDT** [comment]
Works!
