### ISSUE TITLE
Allow users to select a role from the list by clicking on its description

### ISSUE THREAD

**Issue by LucileDT** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/huntington-avenir-bdd#9]
# Context
Currently, when user can assign a responsibility to an account, the for looks like this:
![image](https://user-images.githubusercontent.com/23707217/57319751-9cba4280-70fd-11e9-8fc6-5ac6005dd57c.png)

User can click on the bold label to select the responsibility but they can't do it by clicking on the description. We need to allow it.

# Todo
- [x] create page
- [x] edit page

**Comment by Yann-BUTSCHER-EIRL** [comment]
A tester
